### ISSUE TITLE
Cannot move to Mid Atlantic - "MAO Order Failed: ErrInvalidDestination"

### ISSUE THREAD

**Issue by mccjustin** [spamguy/vue-dipl.io#1]
I play via the browser, both on an iPhone, Mac and PC computer. And on all 3 devices I am unable to move into the Mid Atlantic. This has happened with two separate games, one in which I was Italy and the other France [can you imagine the hardship for France not being able to move into Mid Atl...lets hope I can last/survive ;-)].

I keep getting the message "MAO Order Failed: ErrInvalidDestination."

These are my first two games of Diplicity since playing Droidippy for years, so I am hopeful that this issue can be resolved since I love the game (I was a paid subscriber of Droidippy for some time) OR that I either get to play as Turkey and Russia a lot or that I can always get an English/French alliance.
Hopefully my adversaries don't read this post!

**Comment by spamguy** [comment]
Closing this ticket because this project is barely off the ground and not what you're using.

**Comment by mccjustin** [comment]
ok, my bad. I posted this in two places since I did know which was the correct place.. Sorry, but thanks for the prompt reply and attention to this matter.
